### ISSUE TITLE
BLCOKING CODE

### ISSUE THREAD

**Issue by mossa-Sammer** [muisawe/simple-social-media#8]
https://github.com/muisawe/simple-social-media/blob/969b567840d11cc3040e997fbd53e19553b26cdf/middlewares/is-auth.js#L13

this function call without a callback is synchronys, please provide the callback to avoid blocking, please reed here
https://www.npmjs.com/package/jsonwebtoken#jwtverifytoken-secretorpublickey-options-callback

**Comment by muisawe** [comment]
done
